runtime: java17

instance_class: F2

automatic_scaling:
  min_instances: 0
  max_instances: 10
  target_cpu_utilization: 0.6

env_variables:
  SPRING_PROFILES_ACTIVE: deploy
  DATABASE_URL: jdbc:h2:mem:financialdb
  H2_CONSOLE_ENABLED: false
  CORS_ALLOWED_ORIGINS: "*"
  JAVA_OPTS: "-Xmx512m -Xms256m"

readiness_check:
  path: "/api/v1/llm/health"
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2

liveness_check:
  path: "/api/v1/llm/health"
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 4
  success_threshold: 2