runtime: java17

# App Engine Standard Environment Configuration
# for Financial Advisor LLM API

# Instance configuration
instance_class: F2
automatic_scaling:
  min_instances: 0
  max_instances: 10
  target_cpu_utilization: 0.6
  target_throughput_utilization: 0.6

# Environment variables
env_variables:
  SPRING_PROFILES_ACTIVE: "deploy"
  DATABASE_URL: "jdbc:h2:mem:financialdb"
  H2_CONSOLE_ENABLED: "false"
  CORS_ALLOWED_ORIGINS: "*"
  JAVA_OPTS: "-Xmx512m -Xms256m -XX:+UseG1GC"
  # Add your OpenAI API key here (optional)
  # OPENAI_API_KEY: "your-openai-api-key-here"
  OPENAI_BASE_URL: "https://api.openai.com/v1"

# Health check configuration
readiness_check:
  path: "/api/v1/llm/health"
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2
  app_start_timeout_sec: 300

liveness_check:
  path: "/api/v1/llm/health"
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 4
  success_threshold: 2

# Network settings
network:
  forwarded_ports:
    - 8080

# Note: For Java 17 runtime, file exclusions are handled by .gcloudignore file
# instead of skip_files directive